### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mhopkins-msft**
Edits for readability. Thank you for creating this list!

### CODE REVIEW

**Comment by polymorphic** [comment]
Thanks for the edits. There are some conflicts I can't resolve while oh my phone, will tackle them soon.

**Comment by mhopkins-msft** [comment]
Cool, thanks!

**Comment by o6uoq** [comment]
This PR is almost 4 years old. Are PRs still welcome?

**Comment by polymorphic** [comment]
Absolutely. These changes were merged a while back.

**Comment by mhopkins-msft** [comment]
Hi @polymorphic, the PR was never merged. The live site doesn't have any of these updates.

**Comment by mhopkins-msft** [comment]
More accurately, the **master** branch doesn't have these changes.

**Comment by o6uoq** [comment]
..still not merged!

**Review by polymorphic — APPROVED** [review]

**Pull request closed without merging**
